import axios from '../../app/config/axios.js';

const financeV2Api = {
  getDashboard: (params = {}) => axios.get('/finance-v2/dashboard', { params }),
  getLedger: (params = {}) => axios.get('/finance-v2/ledger', { params }),
  getAccounts: () => axios.get('/finance-v2/accounts'),
  createAccount: (data) => axios.post('/finance-v2/accounts', data),
  getAccountBalances: () => axios.get('/finance-v2/accounts/balances'),
  getFeeAgreements: (params = {}) => axios.get('/finance-v2/fee-agreements', { params }),
  getFeeAgreement: (id) => axios.get(`/finance-v2/fee-agreements/${id}`),
  createFeeAgreement: (data) => axios.post('/finance-v2/fee-agreements', data),
  activateFeeAgreement: (id) => axios.post(`/finance-v2/fee-agreements/${id}/activate`),
  completeFeeAgreement: (id) => axios.post(`/finance-v2/fee-agreements/${id}/complete`),
  cancelFeeAgreement: (id, reason) => axios.post(`/finance-v2/fee-agreements/${id}/cancel`, { reason }),
  getReceivables: (params = {}) => axios.get('/finance-v2/receivables', { params }),
  getReceivable: (id) => axios.get(`/finance-v2/receivables/${id}`),
  createReceivable: (data) => axios.post('/finance-v2/receivables', data),
  postReceivable: (id) => axios.post(`/finance-v2/receivables/${id}/post`),
  getPaymentPlans: (params = {}) => axios.get('/finance-v2/payment-plans', { params }),
  getPaymentPlan: (id) => axios.get(`/finance-v2/payment-plans/${id}`),
  createPaymentPlan: (data) => axios.post('/finance-v2/payment-plans', data),
  activatePaymentPlan: (id) => axios.post(`/finance-v2/payment-plans/${id}/activate`),
  completePaymentPlan: (id) => axios.post(`/finance-v2/payment-plans/${id}/complete`),
  defaultPaymentPlan: (id, reason) => axios.post(`/finance-v2/payment-plans/${id}/default`, { reason }),
  cancelPaymentPlan: (id, reason) => axios.post(`/finance-v2/payment-plans/${id}/cancel`, { reason }),
  createTransaction: (data, idempotencyKey) => axios.post('/finance-v2/transactions', data, { headers: idempotencyKey ? { 'Idempotency-Key': idempotencyKey } : undefined }),
  getTransaction: (id) => axios.get(`/finance-v2/transactions/${id}`),
  reverseTransaction: (id, reason) => axios.post(`/finance-v2/transactions/${id}/reverse`, { reason }),
  reverseTransfer: (transactionId, reason) => axios.post(`/finance-v2/transfers/${transactionId}/reverse`, { reason }),
  refundTransaction: (id, data, idempotencyKey) => axios.post(`/finance-v2/transactions/${id}/refund`, data, { headers: idempotencyKey ? { 'Idempotency-Key': idempotencyKey } : undefined }),
  getExpenses: (params = {}) => axios.get('/finance-v2/expenses', { params }),
  getExpense: (id) => axios.get(`/finance-v2/expenses/${id}`),
  reverseExpense: (id, reason) => axios.post(`/finance-v2/expenses/${id}/reverse`, { reason }),
  createExpense: (data) => axios.post('/finance-v2/expenses', data),
  getPeriods: () => axios.get('/finance-v2/periods'),
  transfer: (data) => axios.post('/finance-v2/transfers', data),
  getClientSummary: (id) => axios.get(`/finance-v2/clients/${id}/summary`),
  getCaseSummary: (id) => axios.get(`/finance-v2/cases/${id}/summary`),
  getConsultationSummary: (id) => axios.get(`/finance-v2/consultations/${id}/summary`),
  getProfitability: (params = {}) => axios.get('/finance-v2/reports/profitability', { params }),
  getReconciliation: () => axios.get('/finance-v2/reports/reconciliation'),
  adjustReceivable: (id, data) => axios.post(`/finance-v2/receivables/${id}/adjustments`, data),
  reverseReceivableAdjustment: (adjustmentId, reason) => axios.post(`/finance-v2/receivable-adjustments/${adjustmentId}/reverse`, { reason }),
  closePeriod: (data) => axios.post('/finance-v2/periods/close', data),
  reopenPeriod: (periodKey, reason) => axios.post(`/finance-v2/periods/${periodKey}/reopen`, { reason }),
  getAudit: (entityType, entityId, params = {}) => axios.get(`/finance-v2/audit/${entityType}/${entityId}`, { params }),
  exportLedger: (params = {}) => axios.get('/finance-v2/reports/ledger.csv', { params, responseType: 'blob' }),
};

export default financeV2Api;
