import { useState } from 'react';
import { AlertTriangle, BarChart3, CheckCircle2, LockKeyhole, Plus, RotateCcw, ShieldCheck } from 'lucide-react';
import Button from '../../components/ui/Button.jsx';
import Badge from '../../components/ui/Badge.jsx';
import { useAuth } from '../../app/providers/auth.provider.jsx';
import { hasPermission, PERMISSION_KEYS } from '../../constants/roles.js';
import { dateTR, money, rowsOf, statusLabel } from '../../features/finance-v2/finance-v2.format.js';
import { useCloseFinancePeriod, useCreateFinanceAccount, useFinanceAccounts, useFinancePeriods, useFinanceProfitability, useFinanceReconciliation, useReopenFinancePeriod } from '../../features/finance-v2/finance-v2.query.js';
const box='rounded-2xl border border-gray-200 bg-white p-5 shadow-sm dark:border-white/[0.07] dark:bg-[#0b1b33]';
export default function FinanceControls(){
 const {user}=useAuth();
 const canAll=hasPermission(user,PERMISSION_KEYS.VIEW_ALL_FINANCE),canProfit=hasPermission(user,PERMISSION_KEYS.VIEW_PROFITABILITY),canReports=hasPermission(user,PERMISSION_KEYS.VIEW_FINANCE_REPORTS),canAccounts=hasPermission(user,PERMISSION_KEYS.MANAGE_FINANCE_ACCOUNTS),canClose=hasPermission(user,PERMISSION_KEYS.CLOSE_FINANCE_PERIOD),canReopen=hasPermission(user,PERMISSION_KEYS.REOPEN_FINANCE_PERIOD);
 const profit=useFinanceProfitability({},canProfit),recon=useFinanceReconciliation(canReports&&canAll),periodsQ=useFinancePeriods(canReports&&canAll),accounts=useFinanceAccounts();
 const createAccount=useCreateFinanceAccount(),close=useCloseFinancePeriod(),reopen=useReopenFinancePeriod();
 const [account,setAccount]=useState({code:'',name:'',account_type:'bank',currency:'TRY',opening_balance:'0'}),[period,setPeriod]=useState(new Date().toISOString().slice(0,7)),[reason,setReason]=useState('');
 const refreshPeriods=()=>periodsQ.refetch?.();
 return <div className="space-y-6"><div><h1 className="text-2xl font-bold">Finans Kontrol Merkezi</h1><p className="mt-1 text-sm text-gray-500">Hesap yönetimi, dönem kilidi, nakit katkı analizi ve legacy mutabakatı.</p></div>
 {canProfit&&<section className={box}><Title icon={BarChart3} t="Nakit Katkı Analizi" s="Tahsilat − iadeler − geri ödenmeyen giderler. Yasal/mali kâr-zarar değildir."/><div className="mt-4 grid gap-3 md:grid-cols-3">{(profit.data?.by_currency||[]).map(x=><div key={x.currency} className="rounded-xl bg-gray-50 p-4 dark:bg-white/[.04]"><b>{x.currency}</b><p className="mt-2 text-2xl font-bold">{money(x.net_cash_contribution,x.currency)}</p><p className="mt-1 text-xs text-gray-500">Tahsilat {money(x.collected,x.currency)} · İade {money(x.refunds,x.currency)} · Gider {money(x.non_reimbursable_expenses,x.currency)}</p></div>)}</div></section>}
 {canReports&&canAll&&<section className={box}><Title icon={recon.data?.status==='ok'?CheckCircle2:AlertTriangle} t="Legacy → Finance V2 Mutabakatı" s="Eski finans kayıtlarının V2'ye taşınma bütünlüğü."/><div className="mt-4 grid gap-3 md:grid-cols-3"><Stat l="Ödemeler" a={recon.data?.payments?.mapped_count} b={recon.data?.payments?.legacy_count}/><Stat l="Planlar" a={recon.data?.plans?.mapped_count} b={recon.data?.plans?.legacy_count}/><Stat l="Taksitler" a={recon.data?.installments?.mapped_count} b={recon.data?.installments?.legacy_count}/></div><div className={`mt-4 rounded-xl p-3 text-sm font-semibold ${recon.data?.status==='ok'?'bg-emerald-50 text-emerald-700':'bg-amber-50 text-amber-700'}`}>{recon.data?.status==='ok'?'Mutabakat temiz görünüyor.':'Dikkat gerektiren legacy farkları var.'}</div>{(recon.data?.payments?.by_currency||[]).length>0&&<div className="mt-3 overflow-x-auto"><table className="w-full text-sm"><thead><tr className="text-left text-xs text-gray-400"><th className="py-2">Para Birimi</th><th>Legacy</th><th>V2</th><th>Fark</th><th>Durum</th></tr></thead><tbody>{recon.data.payments.by_currency.map(x=><tr key={x.currency} className="border-t border-gray-100 dark:border-white/[.06]"><td className="py-2 font-bold">{x.currency}</td><td>{money(x.legacy_amount,x.currency)}</td><td>{money(x.mapped_amount,x.currency)}</td><td>{money(x.difference,x.currency)}</td><td><Badge variant={x.amount_matches?'success':'warning'}>{x.amount_matches?'Eşleşiyor':'Fark Var'}</Badge></td></tr>)}</tbody></table></div>}</section>}
 {canReports&&!canAll&&<section className={box}><Title icon={AlertTriangle} t="Firma Geneli Kontroller" s="Legacy mutabakatı ve dönem listesi VIEW_ALL_FINANCE yetkisi gerektirir."/></section>}
 {canAccounts&&<section className={box}><Title icon={Plus} t="Finans Hesabı Oluştur" s="Kasa/banka hesabı ve açılış bakiyesi."/><form className="mt-4 grid gap-3 md:grid-cols-5" onSubmit={async e=>{e.preventDefault();await createAccount.mutateAsync(account);setAccount({...account,code:'',name:'',opening_balance:'0'})}}>{['code','name','opening_balance'].map(k=><input key={k} required value={account[k]} onChange={e=>setAccount({...account,[k]:e.target.value})} placeholder={{code:'Hesap kodu',name:'Hesap adı',opening_balance:'Açılış bakiyesi'}[k]} className="h-10 rounded-xl border px-3 dark:bg-white/[.04]"/>)}<select value={account.account_type} onChange={e=>setAccount({...account,account_type:e.target.value})} className="rounded-xl border px-3 dark:bg-white/[.04]"><option value="bank">Banka</option><option value="cash">Kasa</option><option value="pos">POS</option><option value="clearing">Takas/Clearing</option><option value="other">Diğer</option></select><div className="flex gap-2"><select value={account.currency} onChange={e=>setAccount({...account,currency:e.target.value})} className="min-w-20 rounded-xl border px-2 dark:bg-white/[.04]"><option>TRY</option><option>USD</option><option>EUR</option><option>GBP</option></select><Button type="submit" loading={createAccount.isPending}>
  Oluştur
</Button></div></form><div className="mt-4 text-xs text-gray-500">Aktif hesap: {rowsOf(accounts.data).length}</div></section>}
 {(canClose||canReopen)&&<section className={box}><Title icon={LockKeyhole} t="Dönem Kontrolü" s="Kapalı döneme finans hareketi yazılamaz. Yeniden açma gerekçesi audit'e kaydedilir."/><div className="mt-4 grid gap-3 md:grid-cols-[180px_1fr_auto_auto]"><input type="month" value={period} onChange={e=>setPeriod(e.target.value)} className="h-10 rounded-xl border px-3 dark:bg-white/[.04]"/><input value={reason} onChange={e=>setReason(e.target.value)} placeholder="Yeniden açma gerekçesi" className="h-10 rounded-xl border px-3 dark:bg-white/[.04]"/>{canClose&&<Button loading={close.isPending} onClick={async()=>{await close.mutateAsync({period_key:period});refreshPeriods()}}><ShieldCheck className="h-4 w-4"/>Dönemi Kapat</Button>}{canReopen&&<Button variant="outline" disabled={!reason.trim()} loading={reopen.isPending} onClick={async()=>{await reopen.mutateAsync({periodKey:period,reason});setReason('');refreshPeriods()}}><RotateCcw className="h-4 w-4"/>Yeniden Aç</Button>}</div>{canReports&&canAll&&<div className="mt-5 space-y-2">{rowsOf(periodsQ.data).map(x=><div key={x.id} className="flex flex-wrap items-center justify-between gap-3 rounded-xl bg-gray-50 px-4 py-3 text-sm dark:bg-white/[.04]"><span><b>{x.period_key}</b><small className="ml-2 text-gray-400">{dateTR(x.starts_on)} – {dateTR(x.ends_on)}</small></span><span className="flex items-center gap-2"><Badge variant={x.status==='closed'?'danger':'success'}>{statusLabel(x.status)}</Badge>{x.reopen_reason&&<small className="max-w-72 truncate text-gray-400">{x.reopen_reason}</small>}</span></div>)}{rowsOf(periodsQ.data).length===0&&<p className="py-4 text-center text-sm text-gray-400">Henüz dönem kaydı yok.</p>}</div>}</section>}
 </div>
}
function Title({icon:Icon,t,s}){return <div className="flex gap-3"><Icon className="mt-0.5 h-5 w-5 text-blue-600"/><div><h2 className="font-bold">{t}</h2><p className="text-xs text-gray-500">{s}</p></div></div>};function Stat({l,a=0,b=0}){return <div className="rounded-xl bg-gray-50 p-4 dark:bg-white/[.04]"><p className="text-xs font-bold uppercase text-gray-400">{l}</p><p className="mt-2 text-xl font-bold">{a} / {b}</p><p className="text-xs text-gray-500">eşleşen / legacy</p></div>}
