import { useMemo, useState } from 'react';
import { Link, useNavigate } from 'react-router-dom';
import { ArrowLeft, Save, WalletCards } from 'lucide-react';
import Button from '../../components/ui/Button.jsx';
import { useFinanceAccounts, useCreateFinanceTransaction, useReceivables } from '../../features/finance-v2/finance-v2.query.js';
import { ContextFields, Field, Select, inputClass, nowLocal, toIso } from './components/FinanceFormBits.jsx';
import { money } from '../../features/finance-v2/finance-v2.format.js';

export default function FinanceV2Create(){
  const navigate=useNavigate(),mutation=useCreateFinanceTransaction(),accountsQ=useFinanceAccounts();
  const [form,setForm]=useState({client_id:'',case_id:'',consultation_id:'',account_id:'',amount:'',currency:'TRY',payment_method:'bank_transfer',transaction_date:nowLocal(),description:'',external_reference:'',base_currency:'TRY',fx_rate:'',allocations:{}});
  const accounts=Array.isArray(accountsQ.data)?accountsQ.data:(accountsQ.data?.rows||[]);
  const receivablesQ=useReceivables({client_id:form.client_id||undefined,currency:form.currency,status:'open',limit:100,offset:0});
  const partialQ=useReceivables({client_id:form.client_id||undefined,currency:form.currency,status:'partially_paid',limit:100,offset:0});
  const receivables=useMemo(()=>[...(receivablesQ.data?.rows||[]),...(partialQ.data?.rows||[])],[receivablesQ.data,partialQ.data]);
  const allocated=useMemo(()=>Object.values(form.allocations).reduce((s,v)=>s+Number(v||0),0),[form.allocations]); const remaining=Math.max(Number(form.amount||0)-allocated,0);
  const set=(name,value)=>setForm(x=>({...x,[name]:value,...(name==='client_id'?{case_id:'',consultation_id:'',allocations:{}}:{}),...(name==='account_id'?{currency:accounts.find(a=>String(a.id)===String(value))?.currency||x.currency,allocations:{}}:{})}));
  const autoAllocate=()=>{let left=Number(form.amount||0);const next={};for(const r of receivables){if(left<=0)break;const cap=Math.max(Number(r.open_balance||0),0);const take=Math.min(left,cap);if(take>0){next[r.id]=take.toFixed(2);left-=take;}}setForm(x=>({...x,allocations:next}));};
  const submit=async(e)=>{e.preventDefault();if(!form.client_id||!form.account_id||Number(form.amount)<=0||allocated>Number(form.amount))return;const allocations=Object.entries(form.allocations).filter(([,v])=>Number(v)>0).map(([receivable_id,amount])=>({receivable_id,amount:String(amount)}));const payload={client_id:form.client_id,case_id:form.case_id||null,consultation_id:form.consultation_id||null,account_id:form.account_id,transaction_type:'receipt',amount:String(form.amount),currency:form.currency,payment_method:form.payment_method,transaction_date:toIso(form.transaction_date),description:form.description,external_reference:form.external_reference,base_currency:form.base_currency,fx_rate:form.currency===form.base_currency?undefined:form.fx_rate,allocations};const res=await mutation.mutateAsync({data:payload,idempotencyKey:crypto.randomUUID()});const id=res?.data?.data?.id||res?.data?.id;navigate(id?`/finance/transactions/${id}`:'/finance');};
  return <div className="mx-auto max-w-5xl space-y-6"><div className="flex items-start gap-3"><Link to="/finance" className="mt-1 rounded-xl border border-gray-200 p-2 text-gray-500 hover:bg-gray-50 dark:border-white/[0.08]"><ArrowLeft className="h-4 w-4"/></Link><div><h1 className="text-2xl font-bold text-gray-900 dark:text-white">Yeni Tahsilat</h1><p className="mt-1 text-sm text-gray-500">Tahsilatı açık alacaklara kısmi veya tam mahsup edin; kalan tutar müvekkil avansı olarak kalır.</p></div></div>
    <form onSubmit={submit} className="space-y-6 rounded-2xl border border-gray-200 bg-white p-6 shadow-sm dark:border-white/[0.07] dark:bg-[#0b1b33]"><div className="flex items-center gap-3 border-b border-gray-100 pb-5 dark:border-white/[0.06]"><div className="rounded-xl bg-blue-50 p-2.5 dark:bg-blue-500/10"><WalletCards className="h-5 w-5 text-blue-600"/></div><div><h2 className="font-bold text-gray-900 dark:text-white">Tahsilat Bilgileri</h2><p className="text-xs text-gray-400">Posted tahsilat düzeltmeleri ters kayıt veya iade ile yapılır.</p></div></div>
      <div className="grid gap-5 md:grid-cols-2"><ContextFields form={form} setForm={setForm}/><Field label="Finans Hesabı"><Select required value={form.account_id} onChange={e=>set('account_id',e.target.value)}><option value="">Hesap seçin</option>{accounts.map(a=><option key={a.id} value={a.id}>{a.name} · {a.currency}</option>)}</Select></Field><Field label="Tutar"><input required min="0.01" step="0.01" type="number" value={form.amount} onChange={e=>set('amount',e.target.value)} className={inputClass}/></Field><Field label="Para Birimi"><input readOnly value={form.currency} className={`${inputClass} bg-gray-50 dark:bg-white/[0.025]`}/></Field>{form.currency!==form.base_currency&&<Field label={`${form.currency}/${form.base_currency} Kuru`} hint="Base tutarın doğru hesaplanması için zorunludur."><input required min="0.0000000001" step="0.000001" type="number" value={form.fx_rate} onChange={e=>set('fx_rate',e.target.value)} className={inputClass}/></Field>}<Field label="İşlem Tarihi"><input required type="datetime-local" value={form.transaction_date} onChange={e=>set('transaction_date',e.target.value)} className={inputClass}/></Field><Field label="Ödeme Yöntemi"><Select value={form.payment_method} onChange={e=>set('payment_method',e.target.value)}><option value="bank_transfer">Banka Havalesi</option><option value="cash">Nakit</option><option value="credit_card">Kredi Kartı</option><option value="check">Çek</option><option value="other">Diğer</option></Select></Field><Field label="Açıklama" full><textarea value={form.description} onChange={e=>set('description',e.target.value)} rows="3" className={`${inputClass} h-auto py-3`}/></Field><Field label="Harici Referans" full><input value={form.external_reference} onChange={e=>set('external_reference',e.target.value)} placeholder="Banka işlem no, dekont referansı vb." className={inputClass}/></Field></div>
      {form.client_id&&<section className="rounded-2xl bg-gray-50 p-4 dark:bg-white/[0.025]"><div className="mb-3 flex flex-wrap items-center justify-between gap-2"><div><h3 className="font-bold text-gray-900 dark:text-white">Alacak Mahsupları</h3><p className="text-xs text-gray-400">Aynı para birimindeki açık tahakkuklar.</p></div><Button size="sm" variant="outline" onClick={autoAllocate} disabled={Number(form.amount)<=0}>Eskiden Yeniye Otomatik Mahsup</Button></div><div className="space-y-2">{receivables.map(r=><div key={r.id} className="grid grid-cols-[1fr_auto] items-center gap-4 rounded-xl bg-white p-3 dark:bg-white/[0.035]"><div className="min-w-0"><p className="truncate text-sm font-semibold">{r.reference_no} · {r.description}</p><p className="text-xs text-gray-400">Açık: {money(r.open_balance,r.currency)}</p></div><input type="number" min="0" max={r.open_balance} step="0.01" value={form.allocations[r.id]||''} onChange={e=>setForm(x=>({...x,allocations:{...x.allocations,[r.id]:e.target.value}}))} className={`${inputClass} w-36`}/></div>)}{!receivables.length&&<p className="py-5 text-center text-sm text-gray-400">Açık tahakkuk yok.</p>}</div><div className={`mt-4 flex flex-wrap justify-between gap-2 rounded-xl p-3 text-sm ${allocated>Number(form.amount||0)?'bg-red-50 text-red-700 dark:bg-red-500/10':'bg-blue-50 text-blue-700 dark:bg-blue-500/10'}`}><span>Mahsup: <b>{money(allocated,form.currency)}</b></span><span>Avans / mahsupsuz kalan: <b>{money(remaining,form.currency)}</b></span></div></section>}
      <div className="flex justify-end gap-2"><Button variant="outline" onClick={()=>navigate('/finance')}>Vazgeç</Button><Button type="submit" loading={mutation.isPending} disabled={!form.client_id||!form.account_id||Number(form.amount)<=0||allocated>Number(form.amount)}><Save className="h-4 w-4"/>Tahsilatı Kaydet</Button></div></form></div>;
}
