import { useMemo, useState } from 'react';
import { Link, useNavigate } from 'react-router-dom';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { ArrowLeft, CalendarClock, Plus, Save, Trash2 } from 'lucide-react';
import Button from '../../components/ui/Button.jsx';
import clientApi from '../../features/clients/client.api.js';
import financeV2Api from '../../features/finance-v2/finance-v2.api.js';
import { FINANCE_V2_KEYS } from '../../features/finance-v2/finance-v2.query.js';
import toast from 'react-hot-toast';

const input='h-11 w-full rounded-xl border border-gray-200 bg-white px-3 text-sm text-gray-800 outline-none transition focus:border-blue-400 focus:ring-2 focus:ring-blue-500/10 dark:border-white/[0.08] dark:bg-white/[0.035] dark:text-white';
const installment=()=>({id:crypto.randomUUID(),title:'',amount:'',due_date:''});
export default function FinanceV2PaymentPlanCreate(){
  const navigate=useNavigate(), qc=useQueryClient();
  const [form,setForm]=useState({client_id:'',case_id:'',title:'',description:'',currency:'TRY',start_date:'',end_date:'',activate:true,installments:[installment()]});
  const clientsQ=useQuery({queryKey:['clients','finance-v2-plan'],queryFn:()=>clientApi.getAll({page:1,limit:100,status:'active'}),staleTime:300000});
  const casesQ=useQuery({queryKey:['clients',form.client_id,'finance-v2-plan-cases'],queryFn:()=>clientApi.getCaseHistory(form.client_id),enabled:Boolean(form.client_id)});
  const clients=Array.isArray(clientsQ.data?.data?.data)?clientsQ.data.data.data:[];
  const cases=useMemo(()=>{const p=casesQ.data?.data?.data??casesQ.data?.data??[];return Array.isArray(p)?p:Array.isArray(p?.cases)?p.cases:[]},[casesQ.data]);
  const total=form.installments.reduce((s,x)=>s+(Number(x.amount)||0),0);
  const mutation=useMutation({mutationFn:(data)=>financeV2Api.createPaymentPlan(data),onSuccess:()=>{qc.invalidateQueries({queryKey:FINANCE_V2_KEYS.all});toast.success('Ödeme planı oluşturuldu');navigate('/finance');},onError:e=>toast.error(e?.response?.data?.message||'Ödeme planı oluşturulamadı')});
  const update=(name,value)=>setForm(x=>({...x,[name]:value,...(name==='client_id'?{case_id:''}:{})}));
  const updateInstallment=(id,name,value)=>setForm(x=>({...x,installments:x.installments.map(i=>i.id===id?{...i,[name]:value}:i)}));
  const submit=e=>{e.preventDefault();if(!form.client_id||!form.title||!form.installments.length||total<=0)return;mutation.mutate({client_id:form.client_id,case_id:form.case_id||null,title:form.title,description:form.description||null,total_amount:total.toFixed(2),currency:form.currency,plan_type:'installment',start_date:form.start_date||null,end_date:form.end_date||null,activate:form.activate,installments:form.installments.map((i,n)=>({installment_number:n+1,title:i.title||`Taksit ${n+1}`,amount:Number(i.amount).toFixed(2),due_date:i.due_date}))});};
  return <div className="mx-auto max-w-5xl space-y-6"><div className="flex items-start gap-3"><Link to="/finance" className="mt-1 rounded-xl border border-gray-200 p-2 text-gray-500 dark:border-white/[0.08]"><ArrowLeft className="h-4 w-4"/></Link><div><h1 className="text-2xl font-bold text-gray-900 dark:text-white">Yeni Ödeme Planı</h1><p className="mt-1 text-sm text-gray-500">Her taksit Finance V2 içinde ayrı bir alacak/tahakkuk kaydına bağlanır.</p></div></div>
  <form onSubmit={submit} className="space-y-6"><section className="rounded-2xl border border-gray-200 bg-white p-6 shadow-sm dark:border-white/[0.07] dark:bg-[#0b1b33]"><h2 className="mb-5 flex items-center gap-2 font-bold text-gray-900 dark:text-white"><CalendarClock className="h-5 w-5 text-blue-600"/>Plan Bilgileri</h2><div className="grid gap-5 md:grid-cols-2"><F label="Müvekkil"><select required className={input} value={form.client_id} onChange={e=>update('client_id',e.target.value)}><option value="">Seçin</option>{clients.map(c=><option key={c.id} value={c.id}>{c.name||c.full_name||c.company_name||c.title||c.id}</option>)}</select></F><F label="Dava"><select className={input} value={form.case_id} onChange={e=>update('case_id',e.target.value)}><option value="">Dava seçilmedi</option>{cases.map(c=><option key={c.id} value={c.id}>{c.case_number||c.title||c.id}</option>)}</select></F><F label="Plan Başlığı"><input required className={input} value={form.title} onChange={e=>update('title',e.target.value)}/></F><F label="Para Birimi"><select className={input} value={form.currency} onChange={e=>update('currency',e.target.value)}><option>TRY</option><option>USD</option><option>EUR</option><option>GBP</option></select></F><F label="Başlangıç"><input type="date" className={input} value={form.start_date} onChange={e=>update('start_date',e.target.value)}/></F><F label="Bitiş"><input type="date" className={input} value={form.end_date} onChange={e=>update('end_date',e.target.value)}/></F><F label="Açıklama" full><textarea rows="3" className={`${input} h-auto py-3`} value={form.description} onChange={e=>update('description',e.target.value)}/></F></div></section>
  <section className="rounded-2xl border border-gray-200 bg-white p-6 shadow-sm dark:border-white/[0.07] dark:bg-[#0b1b33]"><div className="mb-5 flex items-center justify-between"><div><h2 className="font-bold text-gray-900 dark:text-white">Taksitler</h2><p className="text-xs text-gray-400">Toplam: {total.toLocaleString('tr-TR',{minimumFractionDigits:2})} {form.currency}</p></div><Button size="sm" variant="outline" onClick={()=>setForm(x=>({...x,installments:[...x.installments,installment()]}))}><Plus className="h-4 w-4"/>Taksit</Button></div><div className="space-y-3">{form.installments.map((i,n)=><div key={i.id} className="grid gap-3 rounded-xl bg-gray-50 p-4 dark:bg-white/[0.035] md:grid-cols-[70px_1fr_180px_180px_42px] md:items-end"><div className="text-sm font-bold text-gray-400">#{n+1}</div><F label="Başlık"><input className={input} value={i.title} onChange={e=>updateInstallment(i.id,'title',e.target.value)} placeholder={`Taksit ${n+1}`}/></F><F label="Tutar"><input required min="0.01" step="0.01" type="number" className={input} value={i.amount} onChange={e=>updateInstallment(i.id,'amount',e.target.value)}/></F><F label="Vade"><input required type="date" className={input} value={i.due_date} onChange={e=>updateInstallment(i.id,'due_date',e.target.value)}/></F><button type="button" disabled={form.installments.length===1} onClick={()=>setForm(x=>({...x,installments:x.installments.filter(y=>y.id!==i.id)}))} className="flex h-11 w-11 items-center justify-center rounded-xl text-red-500 hover:bg-red-50 disabled:opacity-30"><Trash2 className="h-4 w-4"/></button></div>)}</div></section>
  <div className="flex items-center justify-between"><label className="flex items-center gap-2 text-sm text-gray-600 dark:text-slate-300"><input type="checkbox" checked={form.activate} onChange={e=>update('activate',e.target.checked)}/>Oluşturunca tahakkukları aktifleştir</label><div className="flex gap-2"><Button variant="outline" onClick={()=>navigate('/finance')}>Vazgeç</Button><Button type="submit" loading={mutation.isPending}><Save className="h-4 w-4"/>Planı Kaydet</Button></div></div></form></div>;
}
function F({label,children,full}){return <label className={`space-y-2 ${full?'md:col-span-2':''}`}><span className="text-xs font-bold uppercase tracking-wide text-gray-500 dark:text-slate-400">{label}</span>{children}</label>}
