import { useMemo, useState } from 'react';
import { ArrowLeft, History, RotateCcw, Undo2, WalletCards } from 'lucide-react';
import { Link, useNavigate, useParams } from 'react-router-dom';
import { useAuth } from '../../app/providers/auth.provider.jsx';
import { hasPermission, PERMISSION_KEYS } from '../../constants/roles.js';
import Button from '../../components/ui/Button.jsx';
import Badge from '../../components/ui/Badge.jsx';
import Modal from '../../components/ui/Modal.jsx';
import { useFinanceAccounts, useFinanceAudit, useFinanceTransaction, useRefundFinanceTransaction, useReverseFinanceExpense, useReverseFinanceTransaction, useReverseFinanceTransfer } from '../../features/finance-v2/finance-v2.query.js';
import { auditActionLabel, dateTimeTR, dateTR, money, paymentMethodLabel, statusLabel, transactionLabel } from '../../features/finance-v2/finance-v2.format.js';
import { Field, Select, inputClass, nowLocal, toIso } from './components/FinanceFormBits.jsx';

export default function TransactionDetail(){
 const {id}=useParams(),navigate=useNavigate(),{user}=useAuth(); const q=useFinanceTransaction(id),auditQ=useFinanceAudit('finance_transaction',id),accountsQ=useFinanceAccounts();
 const reverse=useReverseFinanceTransaction(),reverseExpense=useReverseFinanceExpense(),reverseTransfer=useReverseFinanceTransfer(),refund=useRefundFinanceTransaction(); const [modal,setModal]=useState(null); const [reason,setReason]=useState(''); const [refundForm,setRefundForm]=useState({amount:'',account_id:'',transaction_date:nowLocal(),payment_method:'',description:'',fx_rate:'',allocations:{}});
 const tx=q.data||{}; const accounts=Array.isArray(accountsQ.data)?accountsQ.data:(accountsQ.data?.rows||[]); const sameCurrencyAccounts=accounts.filter(a=>a.currency===tx.currency);
 const canReversePermission=hasPermission(user,PERMISSION_KEYS.REVERSE_PAYMENTS),canManageAccounts=hasPermission(user,PERMISSION_KEYS.MANAGE_FINANCE_ACCOUNTS),canAll=hasPermission(user,PERMISSION_KEYS.VIEW_ALL_FINANCE); const refundable=canReversePermission&&tx.transaction_type==='receipt'&&tx.status==='posted'; const isExpense=tx.transaction_type==='expense'; const isTransfer=['transfer_in','transfer_out'].includes(tx.transaction_type); const canReverse=canReversePermission&&tx.status==='posted'&&!['reversal','expense','transfer_in','transfer_out'].includes(tx.transaction_type); const canReverseExpense=canReversePermission&&isExpense&&tx.status==='posted'; const canReverseTransfer=canManageAccounts&&canAll&&isTransfer&&tx.status==='posted';
 const allocTotal=useMemo(()=>Object.values(refundForm.allocations||{}).reduce((s,v)=>s+Number(v||0),0),[refundForm.allocations]);
 const doReverse=async()=>{await reverse.mutateAsync({id,reason});setModal(null);q.refetch();auditQ.refetch();};
 const doReverseExpense=async()=>{await reverseExpense.mutateAsync({id,reason});setModal(null);q.refetch();auditQ.refetch();};
 const doReverseTransfer=async()=>{await reverseTransfer.mutateAsync({transactionId:id,reason});setModal(null);q.refetch();auditQ.refetch();};
 const doRefund=async()=>{const allocations=Object.entries(refundForm.allocations).filter(([,v])=>Number(v)>0).map(([receivable_id,amount])=>({receivable_id,amount:String(amount)}));await refund.mutateAsync({id,data:{amount:String(refundForm.amount),account_id:refundForm.account_id||tx.account_id,transaction_date:toIso(refundForm.transaction_date),payment_method:refundForm.payment_method||tx.payment_method,description:refundForm.description,fx_rate:refundForm.fx_rate||undefined,reason,allocations},idempotencyKey:crypto.randomUUID()});setModal(null);q.refetch();auditQ.refetch();};
 if(q.isLoading)return <div className="py-16 text-center text-sm text-gray-400">İşlem yükleniyor…</div>;
 if(q.error)return <div className="py-16 text-center"><p className="font-semibold">İşlem yüklenemedi.</p><Button className="mt-4" onClick={()=>navigate('/finance')}>Finans Merkezi</Button></div>;
 return <div className="mx-auto max-w-6xl space-y-6"><Header back="/finance" title={`${transactionLabel(tx.transaction_type)} · ${tx.reference_no||''}`} subtitle={`${dateTR(tx.transaction_date)} · ${tx.account_name||'-'}`} />
 <div className="grid gap-5 lg:grid-cols-[1.2fr_.8fr]"><section className="rounded-2xl border border-gray-200 bg-white p-6 shadow-sm dark:border-white/[0.07] dark:bg-[#0b1b33]"><div className="flex flex-wrap items-start justify-between gap-4"><div><p className="text-xs font-bold uppercase text-gray-400">İşlem Tutarı</p><p className={`mt-2 text-3xl font-bold ${tx.direction==='in'?'text-emerald-600':'text-gray-900 dark:text-white'}`}>{tx.direction==='in'?'+':'−'}{money(tx.amount,tx.currency)}</p></div><Badge variant={tx.status==='posted'?'success':tx.status==='reversed'?'danger':'default'}>{statusLabel(tx.status)}</Badge></div><div className="mt-6 grid gap-4 sm:grid-cols-2"><Info label="Tür" value={transactionLabel(tx.transaction_type)}/><Info label="Ödeme Yöntemi" value={paymentMethodLabel(tx.payment_method)}/><Info label="Harici Referans" value={tx.external_reference||'-'}/><Info label="Baz Tutar" value={tx.base_currency?money(tx.base_amount,tx.base_currency):'-'}/><Info label="Kur" value={tx.fx_rate||'-'}/><Info label="Açıklama" value={tx.description||'-'}/></div><div className="mt-6 flex flex-wrap gap-2">{refundable&&<Button variant="warning" onClick={()=>{setReason('');setRefundForm(x=>({...x,amount:'',account_id:tx.account_id,payment_method:tx.payment_method||'',fx_rate:tx.fx_rate||'',allocations:{}}));setModal('refund')}}><Undo2 className="h-4 w-4"/>İade</Button>}{canReverse&&<Button variant="danger" onClick={()=>{setReason('');setModal('reverse')}}><RotateCcw className="h-4 w-4"/>Ters Kayıt</Button>}{canReverseExpense&&<Button variant="danger" onClick={()=>{setReason('');setModal('expense-reverse')}}><RotateCcw className="h-4 w-4"/>Gideri Ters Kaydet</Button>}{canReverseTransfer&&<Button variant="danger" onClick={()=>{setReason('');setModal('transfer-reverse')}}><RotateCcw className="h-4 w-4"/>Transferi Ters Kaydet</Button>}</div></section>
 <section className="rounded-2xl border border-gray-200 bg-white p-6 shadow-sm dark:border-white/[0.07] dark:bg-[#0b1b33]"><h2 className="font-bold text-gray-900 dark:text-white">Mahsuplar</h2><div className="mt-3 space-y-2">{(tx.allocations||[]).map(a=><Link to={`/finance/receivables/${a.receivable_id}`} key={a.id} className="flex justify-between rounded-xl bg-gray-50 p-3 text-sm hover:bg-gray-100 dark:bg-white/[0.035]"><span>{a.receivable_reference}</span><b>{money(a.amount,a.currency)}</b></Link>)}{!(tx.allocations||[]).length&&<p className="py-6 text-center text-sm text-gray-400">Mahsup yok; tutar müvekkil avansı/serbest tahsilat olabilir.</p>}</div>{(tx.refunds||[]).length>0&&<><h3 className="mt-6 text-sm font-bold">İadeler</h3><div className="mt-2 space-y-2">{tx.refunds.map(r=><Link key={r.id} to={`/finance/transactions/${r.id}`} className="flex items-center justify-between gap-3 text-sm text-red-600"><span className="flex items-center gap-2"><span>{r.reference_no}</span>{r.status&&<Badge variant={r.status==='reversed'?'danger':'default'}>{statusLabel(r.status)}</Badge>}</span><b>{money(r.amount,r.currency)}</b></Link>)}</div></>}</section></div>
 <AuditPanel rows={Array.isArray(auditQ.data)?auditQ.data:[]} />
 <Modal isOpen={modal==='reverse'} onClose={()=>setModal(null)} title="Ters Kayıt Oluştur" footer={<><Button variant="outline" onClick={()=>setModal(null)}>Vazgeç</Button><Button variant="danger" loading={reverse.isPending} disabled={!reason.trim()} onClick={doReverse}>Ters Kayıt</Button></>}><p className="mb-4 text-sm text-gray-500">Orijinal kayıt silinmez; karşı yönlü yeni finans hareketi oluşturulur.</p><Field label="Neden"><textarea rows="4" value={reason} onChange={e=>setReason(e.target.value)} className={`${inputClass} h-auto py-3`}/></Field></Modal>
 <Modal isOpen={modal==='expense-reverse'} onClose={()=>setModal(null)} title="Gideri Ters Kaydet" footer={<><Button variant="outline" onClick={()=>setModal(null)}>Vazgeç</Button><Button variant="danger" loading={reverseExpense.isPending} disabled={!reason.trim()} onClick={doReverseExpense}>Gideri Ters Kaydet</Button></>}><p className="mb-4 text-sm text-gray-500">Orijinal gider silinmez; karşı yönlü finans hareketi oluşturularak ters kaydedilir.</p><Field label="Neden"><textarea rows="4" value={reason} onChange={e=>setReason(e.target.value)} className={`${inputClass} h-auto py-3`}/></Field></Modal>
 <Modal isOpen={modal==='transfer-reverse'} onClose={()=>setModal(null)} title="Hesap Transferini Ters Kaydet" footer={<><Button variant="outline" onClick={()=>setModal(null)}>Vazgeç</Button><Button variant="danger" loading={reverseTransfer.isPending} disabled={!reason.trim()} onClick={doReverseTransfer}>Transferi Ters Kaydet</Button></>}><p className="mb-4 text-sm text-gray-500">Transferin giriş ve çıkış ayakları birlikte ters kaydedilir; tek bacaklı finans kaydı oluşmaz.</p><Field label="Neden"><textarea rows="4" value={reason} onChange={e=>setReason(e.target.value)} className={`${inputClass} h-auto py-3`}/></Field></Modal>
 <Modal isOpen={modal==='refund'} onClose={()=>setModal(null)} title="Tahsilat İadesi" size="lg" footer={<><Button variant="outline" onClick={()=>setModal(null)}>Vazgeç</Button><Button variant="warning" loading={refund.isPending} disabled={Number(refundForm.amount)<=0||!reason.trim()} onClick={doRefund}>İadeyi Kaydet</Button></>}><div className="grid gap-4 md:grid-cols-2"><Field label="İade Tutarı"><input type="number" min="0.01" step="0.01" max={tx.amount} value={refundForm.amount} onChange={e=>setRefundForm(x=>({...x,amount:e.target.value}))} className={inputClass}/></Field><Field label="Çıkış Hesabı"><Select value={refundForm.account_id} onChange={e=>setRefundForm(x=>({...x,account_id:e.target.value}))}>{sameCurrencyAccounts.map(a=><option key={a.id} value={a.id}>{a.name} · {a.currency}</option>)}</Select></Field><Field label="Tarih"><input type="datetime-local" value={refundForm.transaction_date} onChange={e=>setRefundForm(x=>({...x,transaction_date:e.target.value}))} className={inputClass}/></Field><Field label="Ödeme Yöntemi"><Select value={refundForm.payment_method} onChange={e=>setRefundForm(x=>({...x,payment_method:e.target.value}))}><option value="bank_transfer">Banka Havalesi</option><option value="cash">Nakit</option><option value="credit_card">Kredi Kartı</option><option value="check">Çek</option><option value="other">Diğer</option></Select></Field>{tx.currency!==tx.base_currency&&<Field label={`${tx.currency}/${tx.base_currency} İade Kuru`} hint="Varsayılan olarak özgün tahsilat kuru gelir; gerekirse iade tarihine göre güncelleyin."><input required min="0.0000000001" step="0.000001" type="number" value={refundForm.fx_rate} onChange={e=>setRefundForm(x=>({...x,fx_rate:e.target.value}))} className={inputClass}/></Field>}<Field label="İade Nedeni" full><textarea rows="3" value={reason} onChange={e=>setReason(e.target.value)} className={`${inputClass} h-auto py-3`}/></Field>{(tx.allocations||[]).length>0&&<div className="md:col-span-2"><p className="mb-2 text-xs font-bold uppercase tracking-wide text-gray-500">Alacak Mahsuplarını Geri Aç</p><div className="space-y-2">{tx.allocations.map(a=><div key={a.id} className="flex items-center gap-3 rounded-xl bg-gray-50 p-3 dark:bg-white/[0.035]"><div className="min-w-0 flex-1"><p className="text-sm font-semibold">{a.receivable_reference}</p><p className="text-xs text-gray-400">Özgün mahsup: {money(a.amount,a.currency)}</p></div><input type="number" min="0" max={a.amount} step="0.01" value={refundForm.allocations[a.receivable_id]||''} onChange={e=>setRefundForm(x=>({...x,allocations:{...x.allocations,[a.receivable_id]:e.target.value}}))} className={`${inputClass} max-w-36`}/></div>)}</div><p className="mt-2 text-xs text-gray-400">Seçilen geri açma toplamı: {money(allocTotal,tx.currency)}. Kalan kısım yalnız kullanılabilir müvekkil avansı varsa mahsupsuz iade edilir.</p></div>}</div></Modal>
 </div>;
}
export function Header({back,title,subtitle}){return <div className="flex items-start gap-3"><Link to={back} className="mt-1 rounded-xl border border-gray-200 p-2 text-gray-500 hover:bg-gray-50 dark:border-white/[0.08]"><ArrowLeft className="h-4 w-4"/></Link><div className="flex h-11 w-11 items-center justify-center rounded-xl bg-blue-50 dark:bg-blue-500/10"><WalletCards className="h-5 w-5 text-blue-600"/></div><div><h1 className="text-2xl font-bold text-gray-900 dark:text-white">{title}</h1><p className="mt-1 text-sm text-gray-500">{subtitle}</p></div></div>}
function Info({label,value}){return <div><p className="text-xs font-bold uppercase text-gray-400">{label}</p><p className="mt-1 text-sm font-semibold text-gray-800 dark:text-slate-200">{value}</p></div>}
export function AuditPanel({rows}){return <section className="rounded-2xl border border-gray-200 bg-white p-6 shadow-sm dark:border-white/[0.07] dark:bg-[#0b1b33]"><div className="flex items-center gap-2"><History className="h-4 w-4 text-blue-600"/><h2 className="font-bold text-gray-900 dark:text-white">Finans İşlem Geçmişi</h2></div><div className="mt-4 space-y-3">{rows.map(x=><div key={x.id} className="border-l-2 border-blue-200 pl-4 dark:border-blue-500/30"><div className="flex flex-wrap justify-between gap-2"><b className="text-sm">{auditActionLabel(x.action)}</b><span className="text-xs text-gray-400">{dateTimeTR(x.created_at)}</span></div>{x.reason&&<p className="mt-1 text-xs text-gray-500">{x.reason}</p>}</div>)}{!rows.length&&<p className="py-5 text-center text-sm text-gray-400">İşlem geçmişi kaydı yok.</p>}</div></section>}
