import express from 'express';
import { authenticate, authorizePermission } from '../../middlewares/auth.middleware.js';
import { PERMISSION_KEYS } from '../../constants/roles.js';
import { financeV2Controller } from './finance-v2.controller.js';
const router=express.Router();
router.use(authenticate);
router.get('/accounts',authorizePermission(PERMISSION_KEYS.VIEW_FINANCE),financeV2Controller.listAccounts);
router.post('/accounts',authorizePermission(PERMISSION_KEYS.MANAGE_FINANCE_ACCOUNTS),financeV2Controller.createAccount);
router.get('/fee-agreements',authorizePermission(PERMISSION_KEYS.VIEW_FINANCE),financeV2Controller.listFeeAgreements);
router.get('/fee-agreements/:id',authorizePermission(PERMISSION_KEYS.VIEW_FINANCE),financeV2Controller.getFeeAgreement);
router.post('/fee-agreements',authorizePermission(PERMISSION_KEYS.MANAGE_FEE_AGREEMENTS),financeV2Controller.createFeeAgreement);
router.post('/fee-agreements/:id/activate',authorizePermission(PERMISSION_KEYS.MANAGE_FEE_AGREEMENTS),financeV2Controller.activateFeeAgreement);
router.post('/fee-agreements/:id/complete',authorizePermission(PERMISSION_KEYS.MANAGE_FEE_AGREEMENTS),financeV2Controller.completeFeeAgreement);
router.post('/fee-agreements/:id/cancel',authorizePermission(PERMISSION_KEYS.MANAGE_FEE_AGREEMENTS),financeV2Controller.cancelFeeAgreement);
router.get('/payment-plans',authorizePermission(PERMISSION_KEYS.VIEW_FINANCE),financeV2Controller.listPaymentPlans);
router.get('/payment-plans/:id',authorizePermission(PERMISSION_KEYS.VIEW_FINANCE),financeV2Controller.getPaymentPlan);
router.post('/payment-plans',authorizePermission(PERMISSION_KEYS.MANAGE_PAYMENT_PLANS),financeV2Controller.createPaymentPlan);
router.post('/payment-plans/:id/activate',authorizePermission(PERMISSION_KEYS.MANAGE_PAYMENT_PLANS),financeV2Controller.activatePaymentPlan);
router.post('/payment-plans/:id/complete',authorizePermission(PERMISSION_KEYS.MANAGE_PAYMENT_PLANS),financeV2Controller.completePaymentPlan);
router.post('/payment-plans/:id/default',authorizePermission(PERMISSION_KEYS.MANAGE_PAYMENT_PLANS),financeV2Controller.defaultPaymentPlan);
router.post('/payment-plans/:id/cancel',authorizePermission(PERMISSION_KEYS.MANAGE_PAYMENT_PLANS),financeV2Controller.cancelPaymentPlan);
router.get('/receivables',authorizePermission(PERMISSION_KEYS.VIEW_FINANCE),financeV2Controller.listReceivables);
router.get('/receivables/:id',authorizePermission(PERMISSION_KEYS.VIEW_FINANCE),financeV2Controller.getReceivable);
router.post('/receivables',authorizePermission(PERMISSION_KEYS.CREATE_RECEIVABLES),financeV2Controller.createReceivable);
router.post('/receivables/:id/post',authorizePermission(PERMISSION_KEYS.CREATE_RECEIVABLES),financeV2Controller.postReceivable);
router.post('/receivables/:id/adjustments',authorizePermission(PERMISSION_KEYS.CREATE_RECEIVABLES),financeV2Controller.adjustReceivable);
router.post('/receivable-adjustments/:adjustmentId/reverse',authorizePermission(PERMISSION_KEYS.REVERSE_PAYMENTS),financeV2Controller.reverseReceivableAdjustment);
router.get('/transactions/:id',authorizePermission(PERMISSION_KEYS.VIEW_FINANCE),financeV2Controller.getTransaction);
router.post('/transactions',authorizePermission(PERMISSION_KEYS.RECORD_PAYMENTS),financeV2Controller.createTransaction);
router.post('/transactions/:id/reverse',authorizePermission(PERMISSION_KEYS.REVERSE_PAYMENTS),financeV2Controller.reverseTransaction);
router.post('/transactions/:id/refund',authorizePermission(PERMISSION_KEYS.REVERSE_PAYMENTS),financeV2Controller.refundTransaction);
router.post('/transfers/:transactionId/reverse',authorizePermission(PERMISSION_KEYS.MANAGE_FINANCE_ACCOUNTS),financeV2Controller.reverseTransfer);
router.post('/transfers',authorizePermission(PERMISSION_KEYS.MANAGE_FINANCE_ACCOUNTS),financeV2Controller.transfer);
router.get('/dashboard',authorizePermission(PERMISSION_KEYS.VIEW_FINANCE_REPORTS),financeV2Controller.dashboard);
router.get('/ledger',authorizePermission(PERMISSION_KEYS.VIEW_FINANCE),financeV2Controller.ledger);
router.get('/reports/profitability',authorizePermission(PERMISSION_KEYS.VIEW_PROFITABILITY),financeV2Controller.profitability);
router.get('/reports/reconciliation',authorizePermission(PERMISSION_KEYS.VIEW_FINANCE_REPORTS),financeV2Controller.legacyReconciliation);
router.get('/audit/:entityType/:entityId',authorizePermission(PERMISSION_KEYS.VIEW_FINANCE),financeV2Controller.auditTimeline);
router.get('/reports/ledger.csv',authorizePermission(PERMISSION_KEYS.EXPORT_FINANCE),financeV2Controller.exportLedgerCsv);
router.get('/reports/ledger.xlsx',authorizePermission(PERMISSION_KEYS.EXPORT_FINANCE),financeV2Controller.exportLedgerXlsx);
router.get('/reports/ledger.pdf',authorizePermission(PERMISSION_KEYS.EXPORT_FINANCE),financeV2Controller.exportLedgerPdf);
router.get('/accounts/balances',authorizePermission(PERMISSION_KEYS.VIEW_FINANCE_REPORTS),financeV2Controller.accountBalances);
router.get('/expenses',authorizePermission(PERMISSION_KEYS.VIEW_FINANCE),financeV2Controller.listExpenses);
router.get('/expenses/:id',authorizePermission(PERMISSION_KEYS.VIEW_FINANCE),financeV2Controller.getExpense);
router.post('/expenses/:id/reverse',authorizePermission(PERMISSION_KEYS.REVERSE_PAYMENTS),financeV2Controller.reverseExpense);
router.post('/expenses',authorizePermission(PERMISSION_KEYS.CREATE_EXPENSES),financeV2Controller.createExpense);
router.get('/periods',authorizePermission(PERMISSION_KEYS.VIEW_FINANCE_REPORTS),financeV2Controller.listPeriods);
router.post('/periods/close',authorizePermission(PERMISSION_KEYS.CLOSE_FINANCE_PERIOD),financeV2Controller.closePeriod);
router.post('/periods/:periodKey/reopen',authorizePermission(PERMISSION_KEYS.REOPEN_FINANCE_PERIOD),financeV2Controller.reopenPeriod);
router.get('/clients/:clientId/summary',authorizePermission(PERMISSION_KEYS.VIEW_FINANCE),financeV2Controller.clientSummary);
router.get('/cases/:caseId/summary',authorizePermission(PERMISSION_KEYS.VIEW_FINANCE),financeV2Controller.caseSummary);
router.get('/consultations/:consultationId/summary',authorizePermission(PERMISSION_KEYS.VIEW_FINANCE),financeV2Controller.consultationSummary);
export { router as financeV2Routes };
